@echo off
echo Testing OrbosisNGO Backend Server...
echo.

echo Step 1: Installing dependencies...
call npm install

echo.
echo Step 2: Creating uploads directory...
if not exist "uploads" mkdir uploads

echo.
echo Step 3: Running fix script...
node fix-500-error.js

echo.
echo Step 4: Testing debug server...
echo Starting debug server on port 3003...
start /B node debug-server.js
timeout /t 3 /nobreak > nul

echo.
echo Step 5: Testing main server...
echo Starting main server...
npm start